INSERT INTO products (title, stock, price) VALUES ('Laptop', 50, 1200.99);
INSERT INTO products (title, stock, price) VALUES ('Smartphone', 100, 799.99);
INSERT INTO products (title, stock, price) VALUES ('Tablet', 75, 499.99);
INSERT INTO products (title, stock, price) VALUES ('Headphones', 200, 149.99);
INSERT INTO products (title, stock, price) VALUES ('Keyboard', 150, 59.99);
INSERT INTO products (title, stock, price) VALUES ('Mouse', 300, 29.99);
INSERT INTO products (title, stock, price) VALUES ('Monitor', 60, 299.99);
INSERT INTO products (title, stock, price) VALUES ('Printer', 40, 199.99);
INSERT INTO products (title, stock, price) VALUES ('External Hard Drive', 90, 89.99);
INSERT INTO products (title, stock, price) VALUES ('USB Flash Drive', 500, 19.99);
INSERT INTO products (title, stock, price) VALUES ('Smartwatch', 120, 249.99);
INSERT INTO products (title, stock, price) VALUES ('Bluetooth Speaker', 180, 79.99);
INSERT INTO products (title, stock, price) VALUES ('Gaming Console', 70, 499.99);
INSERT INTO products (title, stock, price) VALUES ('Camera', 55, 699.99);
INSERT INTO products (title, stock, price) VALUES ('Router', 85, 99.99);
INSERT INTO products (title, stock, price) VALUES ('Power Bank', 250, 39.99);
INSERT INTO products (title, stock, price) VALUES ('Earbuds', 400, 129.99);
INSERT INTO products (title, stock, price) VALUES ('Fitness Tracker', 130, 149.99);
INSERT INTO products (title, stock, price) VALUES ('Charger', 600, 15.99);
INSERT INTO products (title, stock, price) VALUES ('Webcam', 95, 49.99);